version: '3'

services:

  db:
    image: mysql:5.6.33
    volumes:
      - wagtail_mysql_data:/var/lib/mysql
    ports:
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=wagtail

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - db
      - elasticsearch
    tty: true
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=yougov.settings.dev
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=wagtail
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - ELASTIC_HOST=elasticsearch
      - ELASTIC_PORT=9200

    command: >
      bash -c "python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

  elasticsearch:
    image: elasticsearch:5.4.0
    depends_on:
      - db
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    volumes:
      - wagtail_es_data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300

volumes:
  wagtail_mysql_data:
  wagtail_es_data:

