# Generated by Django 2.2.4 on 2019-08-09 11:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190809_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='article_description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
