# Generated by Django 2.2.4 on 2019-08-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newspage_link_tab_chooser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='link_tab_chooser',
            field=models.CharField(choices=[('_blank', 'New tab'), ('_self', 'Current tab')], default='_self', max_length=6),
        ),
    ]
