# Generated by Django 2.2.3 on 2019-07-19 14:36

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190719_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='content',
            field=wagtail.core.fields.StreamField([('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add addition text', required=True))])), ('quotation_block', wagtail.core.blocks.StructBlock([('quotation', wagtail.core.blocks.TextBlock(help_text='Add your quote', required=True)), ('citation', wagtail.core.blocks.TextBlock(help_text='add citation', required=True)), ('background', wagtail.core.blocks.ChoiceBlock(choices=[('#F5F6F7', 'Grey'), ('#FFFFFF', 'White')], help_text='choose color'))])), ('full_rich_text', streams.blocks.RichTextBlock()), ('video_block', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.TextBlock(help_text='add your header', required=True)), ('sub_copy', wagtail.core.blocks.TextBlock(help_text='add your sub_copy', required=True)), ('video_thumbnail', wagtail.images.blocks.ImageChooserBlock(help_text='choose video thumbnail image', required=True)), ('media_chooser', wagtail.core.blocks.StreamBlock([('video_url', wagtail.embeds.blocks.EmbedBlock()), ('video_file', streams.blocks.TestMediaBlock(icon='media'))], max_num=1))])), ('image_block', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.TextBlock(help_text='add your header', required=True)), ('header_color', wagtail.core.blocks.ChoiceBlock(choices=[('#FFFFFF', 'White'), ('#000000', 'Black')], help_text='choose header color')), ('sub_copy', wagtail.core.blocks.TextBlock(help_text='add your sub_copy', required=True)), ('sub_copy_color', wagtail.core.blocks.ChoiceBlock(choices=[('#FFFFFF', 'White'), ('#000000', 'Black')], help_text='choose sub copy color')), ('link_text', wagtail.core.blocks.CharBlock(max_length=128, required=True)), ('link_url', wagtail.core.blocks.URLBlock(help_text='add url', required=True)), ('link_tab_chooser', wagtail.core.blocks.ChoiceBlock(choices=[('_self', 'Current Tab'), ('_blank', 'New Tab')], help_text='choose either open image on new or current tab')), ('link_media_content', wagtail.core.blocks.TextBlock(help_text='for now idk for what')), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='choose image', required=True))])), ('image_person_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='choose image', required=True)), ('name', wagtail.core.blocks.CharBlock(help_text='add name and surname', max_length=32, required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='add title', max_length=32, required=True)), ('biography', wagtail.core.blocks.TextBlock(help_text='biography about', required=True))])), ('image_people_block', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='choose image', required=True)), ('name', wagtail.core.blocks.CharBlock(help_text='add name and surname', max_length=32, required=True)), ('title', wagtail.core.blocks.CharBlock(help_text='add title', max_length=32, required=True)), ('biography', wagtail.core.blocks.TextBlock(help_text='biography about', required=True))])))])), ('image_content_block', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='choose image', required=True)), ('caption', wagtail.core.blocks.TextBlock(help_text='add caption', required=True))])), ('callout_stream_block', wagtail.core.blocks.StreamBlock([('content', wagtail.core.blocks.StructBlock([('callout', wagtail.core.blocks.TextBlock(help_text='add your callout', required=True)), ('header', wagtail.core.blocks.TextBlock(help_text='add your header', required=True)), ('sub_copy', wagtail.core.blocks.TextBlock(help_text='add your sub_copy', required=True)), ('background', wagtail.core.blocks.ChoiceBlock(choices=[('#F5F6F7', 'Grey'), ('#FFFFFF', 'White')], help_text='choose color'))], help_text='You can add max 3 callouts', required=True))]))], blank=True, null=True),
        ),
    ]
