# Generated by Django 2.2.3 on 2019-07-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190724_1328'),
        ('home', '0010_auto_20190724_0942'),
    ]

    operations = [
    ]
