# Generated by Django 2.2.3 on 2019-07-30 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190729_2029'),
        ('home', '0014_auto_20190729_1940'),
    ]

    operations = [
    ]
