# Generated by Django 2.2.4 on 2019-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20190828_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='is_timestamp_displayed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Display published date'),
        ),
    ]
