# Generated by Django 2.2.3 on 2019-07-30 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0012_auto_20190729_2029'),
        ('flex', '0011_auto_20190729_1940'),
    ]

    operations = [
    ]
