# Generated by Django 2.2.4 on 2019-08-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0002_auto_20190821_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='address',
        ),
        migrations.AddField(
            model_name='office',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='address_line_3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='office',
            name='office_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='OfficeLocationDetail',
        ),
    ]
