# Generated by Django 2.2.4 on 2019-08-21 13:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0004_auto_20190821_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('is_headquarter', models.NullBooleanField()),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=255, null=True)),
                ('tel', models.CharField(blank=True, max_length=255, null=True)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('web', models.URLField(blank=True, null=True)),
                ('did_you_know', models.TextField(blank=True, null=True)),
                ('office_component', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_offices', to='office.OfficeComponent')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OfficeHQ',
        ),
    ]
