# Generated by Django 2.2.3 on 2019-07-02 12:07

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('custom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersnippet',
            name='copyright_message',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='footersnippet',
            name='footer_text',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footersnippet',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
