# Generated by Django 2.2.3 on 2019-07-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_auto_20190702_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersnippet',
            name='name',
            field=models.CharField(default='base', help_text='Name of a footer', max_length=16),
            preserve_default=False,
        ),
    ]
