# Generated by Django 2.2.3 on 2019-07-02 13:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0003_footersnippet_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersnippet',
            name='policy_links',
            field=wagtail.core.fields.StreamField([('policy_link', wagtail.core.blocks.StructBlock([('link_name', wagtail.core.blocks.TextBlock(help_text='add your callout', required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(help_text='choose page'))]))], blank=True, null=True),
        ),
    ]
