# Generated by Django 2.2.3 on 2019-07-04 12:33

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0005_auto_20190702_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersnippet',
            name='social_channel_links',
            field=wagtail.core.fields.StreamField([('social_channel_links', wagtail.core.blocks.StructBlock([('social_channel_logo', wagtail.images.blocks.ImageChooserBlock(help_text='choose social channel logo', required=True)), ('social_channel_url', wagtail.core.blocks.URLBlock(help_text='add url', required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footersnippet',
            name='global_links',
            field=wagtail.core.fields.StreamField([('global_link', wagtail.core.blocks.StructBlock([('link_name', wagtail.core.blocks.TextBlock(help_text='add your callout', required=True)), ('link_page', wagtail.core.blocks.URLBlock(help_text='add url', required=True)), ('link_tab_chooser', wagtail.core.blocks.ChoiceBlock(choices=[('_self', 'Current Tab'), ('_blank', 'New Tab')], help_text='choose either open image on new or current tab'))]))], blank=True, null=True),
        ),
    ]
