# Generated by Django 2.2.3 on 2019-07-08 08:33

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('custom', '0006_auto_20190704_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersnippet',
            name='global_links',
            field=wagtail.core.fields.StreamField([('global_link', wagtail.core.blocks.StructBlock([('link_name', wagtail.core.blocks.TextBlock(help_text='add your link name', required=True)), ('link_page', wagtail.core.blocks.URLBlock(help_text='add url', required=True)), ('link_tab_chooser', wagtail.core.blocks.ChoiceBlock(choices=[('_self', 'Current Tab'), ('_blank', 'New Tab')], help_text='choose either open image on new or current tab'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footersnippet',
            name='policy_links',
            field=wagtail.core.fields.StreamField([('policy_link', wagtail.core.blocks.StructBlock([('link_name', wagtail.core.blocks.TextBlock(help_text='add your link name', required=True)), ('link_page', wagtail.core.blocks.PageChooserBlock(help_text='choose internal page', required=True)), ('link_tab_chooser', wagtail.core.blocks.ChoiceBlock(choices=[('_self', 'Current Tab'), ('_blank', 'New Tab')], help_text='choose either open image on new or current tab'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footersnippet',
            name='site_links',
            field=wagtail.core.fields.StreamField([('site_link', wagtail.core.blocks.StructBlock([('link_name', wagtail.core.blocks.TextBlock(help_text='add your link name', required=True)), ('link_page', wagtail.core.blocks.StreamBlock([('link_external_url', wagtail.core.blocks.URLBlock(help_text='add url', required=True)), ('link_internal_page', wagtail.core.blocks.PageChooserBlock(help_text='choose page', required=True))], help_text='choose one type of url you want to use', required=True)), ('link_tab_chooser', wagtail.core.blocks.ChoiceBlock(choices=[('_self', 'Current Tab'), ('_blank', 'New Tab')], help_text='choose either open image on new or current tab'))]))], blank=True, null=True),
        ),
        migrations.CreateModel(
            name='MenuSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of a footer', max_length=16)),
                ('menu_tab_chooser', models.CharField(choices=[('_self', 'Current tab'), ('_blank', 'New tab')], default='_self', max_length=16)),
                ('menu_links', wagtail.core.fields.StreamField([('social_channel_links', wagtail.core.blocks.StructBlock([('menu_navigation_level_1', wagtail.core.blocks.StreamBlock([('menu_external_url', wagtail.core.blocks.StructBlock([('displayed_name', wagtail.core.blocks.CharBlock(max_length=16, required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='add url', required=True))], help_text='choose url', required=True)), ('menu_internal_page', wagtail.core.blocks.PageChooserBlock(help_text='choose page', required=True))], help_text='choose page', required=True)), ('menu_navigation_level_2', wagtail.core.blocks.StreamBlock([('menu_external_url', wagtail.core.blocks.StructBlock([('displayed_name', wagtail.core.blocks.CharBlock(max_length=16, required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='add url', required=True))], help_text='choose url', required=True)), ('menu_internal_page', wagtail.core.blocks.PageChooserBlock(help_text='choose page', required=True))], help_text='add nested pages', required=False))]))], blank=True, null=True)),
                ('logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
        ),
    ]
