# Generated by Django 2.2.3 on 2019-07-16 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0008_auto_20190716_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menusnippet',
            old_name='social_channel_links_mobile_menu',
            new_name='social_channel_links',
        ),
    ]
