# Generated by Django 2.2.3 on 2019-07-19 10:17

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0009_auto_20190716_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersnippet',
            name='copyright_message',
        ),
        migrations.AlterField(
            model_name='menusnippet',
            name='menu_links',
            field=wagtail.core.fields.StreamField([('social_channel_links', wagtail.core.blocks.StructBlock([('menu_navigation_level_1', wagtail.core.blocks.StreamBlock([('menu_external_url', wagtail.core.blocks.StructBlock([('displayed_name', wagtail.core.blocks.CharBlock(max_length=16, required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='add url', required=True))], help_text='choose url', required=True)), ('menu_internal_page', wagtail.core.blocks.PageChooserBlock(help_text='choose page', required=True))], help_text='choose page', required=True)), ('navigation_html_id', wagtail.core.blocks.CharBlock(max_length=16, required=True)), ('menu_navigation_level_2', wagtail.core.blocks.StreamBlock([('menu_external_url', wagtail.core.blocks.StructBlock([('displayed_name', wagtail.core.blocks.CharBlock(max_length=16, required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='add url', required=True))], help_text='choose url', required=True)), ('menu_internal_page', wagtail.core.blocks.PageChooserBlock(help_text='choose page', required=True))], help_text='add nested pages', required=False))]))], blank=True, null=True),
        ),
    ]
