# Generated by Django 2.2.3 on 2019-07-22 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0010_auto_20190719_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersnippet',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='menusnippet',
            name='logo',
        ),
    ]
