# Generated by Django 2.2.3 on 2019-07-22 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0011_auto_20190722_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of a cookie snippet', max_length=16)),
                ('text', models.TextField(help_text='cookie main text')),
                ('opt_in', models.CharField(help_text='button accept text', max_length=32)),
                ('opt_out', models.CharField(help_text='button reject text', max_length=32)),
            ],
        ),
    ]
