# Generated by Django 2.2.3 on 2019-07-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0012_cookiesnippet'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiesnippet',
            name='ga_id',
            field=models.CharField(blank=True, help_text='Google Analytics ID', max_length=32, null=True),
        ),
    ]
