# Generated by Django 2.2.4 on 2019-08-12 08:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0013_cookiesnippet_ga_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusnippet',
            name='global_navigation_link',
            field=wagtail.core.fields.StreamField([('global_navigation_link', wagtail.core.blocks.StructBlock([('global_link', wagtail.core.blocks.StreamBlock([('menu_external_url', wagtail.core.blocks.StructBlock([('displayed_name', wagtail.core.blocks.CharBlock(max_length=32, required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='add url', required=True))], help_text='choose url', required=True)), ('menu_internal_page', wagtail.core.blocks.PageChooserBlock(help_text='choose page', required=True))])), ('link_tab_chooser', wagtail.core.blocks.ChoiceBlock(choices=[('_self', 'Current Tab'), ('_blank', 'New Tab')], help_text='choose either open image on new or current tab'))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='footersnippet',
            name='social_channel_links',
            field=wagtail.core.fields.StreamField([('social_channel_links', wagtail.core.blocks.StructBlock([('social_channel_logo', wagtail.core.blocks.ChoiceBlock(choices=[('facebook', 'facebook'), ('twitter', 'twitter'), ('instagram', 'instagram'), ('rss', 'rss'), ('linkedin', 'linkedin')], help_text='choose social channel logo')), ('social_channel_url', wagtail.core.blocks.URLBlock(help_text='add url', required=True))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menusnippet',
            name='menu_links',
            field=wagtail.core.fields.StreamField([('social_channel_links', wagtail.core.blocks.StructBlock([('menu_navigation_level_1', wagtail.core.blocks.StreamBlock([('menu_external_url', wagtail.core.blocks.StructBlock([('displayed_name', wagtail.core.blocks.CharBlock(max_length=32, required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='add url', required=True))], help_text='choose url', required=True)), ('menu_internal_page', wagtail.core.blocks.PageChooserBlock(help_text='choose page', required=True))], help_text='choose page', required=True)), ('navigation_html_id', wagtail.core.blocks.CharBlock(max_length=16, required=True)), ('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(help_text='Link or file title', max_length=255, required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('link', wagtail.core.blocks.StreamBlock([('menu_external_url', wagtail.core.blocks.StructBlock([('displayed_name', wagtail.core.blocks.CharBlock(max_length=32, required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='add url', required=True))], help_text='choose url', required=True)), ('menu_internal_page', wagtail.core.blocks.PageChooserBlock(help_text='choose page', required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(help_text='choose doc file', required=True))], required=True))])), ('menu_navigation_level_2', wagtail.core.blocks.StreamBlock([('menu_external_url', wagtail.core.blocks.StructBlock([('displayed_name', wagtail.core.blocks.CharBlock(max_length=32, required=True)), ('url', wagtail.core.blocks.URLBlock(help_text='add url', required=True))], help_text='choose url', required=True)), ('menu_internal_page', wagtail.core.blocks.PageChooserBlock(help_text='choose page', required=True))], help_text='add nested pages', required=False))]))], blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menusnippet',
            name='social_channel_links',
            field=wagtail.core.fields.StreamField([('social_channel_links', wagtail.core.blocks.StructBlock([('social_channel_logo', wagtail.core.blocks.ChoiceBlock(choices=[('facebook', 'facebook'), ('twitter', 'twitter'), ('instagram', 'instagram'), ('rss', 'rss'), ('linkedin', 'linkedin')], help_text='choose social channel logo')), ('social_channel_url', wagtail.core.blocks.URLBlock(help_text='add url', required=True))]))], blank=True, null=True),
        ),
    ]
