# Generated by Django 2.2.4 on 2019-08-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0014_auto_20190812_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='menusnippet',
            name='global_navigation_text',
            field=models.CharField(blank=True, default='Our other sites:', max_length=255, null=True),
        ),
    ]
